package net.startingpoint;

public interface GlobalConstants {
	public static final String IDENTIFIER_NAME = "identifier";
	
	public static final int TIME_OUT = 30000;
	
	public static final int CONNECTION_ESTABLISH_SUCCESS = 0x01, CONNECTION_ESTABLISH_FAILURE = 0x02, CONNECTION_ESTABLISH_BAD_USERNAME = 0x03;
	public static final int GEO_POINT_RECEIVED = 0x04, MULTIPLE_GEO_POINT_RECEIVED = 0x05, GEO_POINT_REMOVE = 0x06;
	public static final int CONNECTION_LOST = 0x07;

	public static final int GENDER_OVERLAYIMAGE_MALE = 0x0001, 
			GENDER_OVERLAYIMAGE_FEMALE = 0x0002;
	
	public static final int BG_OVERLAYERIMAGE_GRAY = 0x0004,
			BG_OVERLAYERIMAGE_PURPLE = 0x0008,
			BG_OVERLAYERIMAGE_DARKBLUE = 0x0010,
			BG_OVERLAYERIMAGE_LIGHTBLUE = 0x0020,
			BG_OVERLAYERIMAGE_TURKISH = 0x0040, 
			BG_OVERLAYERIMAGE_GREEN = 0x0080,
			BG_OVERLAYERIMAGE_YELLOW = 0x0100, 
			BG_OVERLAYERIMAGE_ORANGE = 0x0200,
			BG_OVERLAYERIMAGE_RED = 0x0400;
}
